# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediator_app', '0005_auto_20180124_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=100)),
                ('med_use', models.CharField(max_length=255)),
                ('med_barcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('use', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.Medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.User')),
            ],
        ),
    ]
