# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediator_app', '0006_medicine_usermedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedicine',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='usermedicine',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMedicine',
        ),
    ]
