# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediator_app', '0007_auto_20180124_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
