# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediator_app', '0017_auto_20180125_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('med_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=100)),
                ('med_use', models.CharField(max_length=255)),
                ('med_barcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedicine',
            fields=[
                ('user_med_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField()),
                ('use', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.Medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.User')),
            ],
        ),
    ]
