# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediator_app', '0021_auto_20180127_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.User')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.Volunteer')),
            ],
        ),
    ]
