# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediator_app', '0027_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.Medicine')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
