# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediator_app', '0028_auto_20180127_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='medicine_stock',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Medicine_Stock',
        ),
    ]
