# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediator_app', '0031_auto_20180127_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.Medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.User')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediator_app.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediator_app.Medicine')),
            ],
        ),
    ]
